services:
  - type: web
    name: zenith-bot-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - fromGroup: zenith-secrets
    nativeEnvironment:
      systemPackages:
        - build-essential
        - libta-lib-dev

  - type: static
    name: zenith-trading-bot
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    envVars:
      - key: VITE_APP_API_URL
        value: "https://zenith-bot-backend.onrender.com"