services:
  - type: web
    name: zenith-bot-backend
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - fromGroup: zenith-secrets

  - type: static
    name: zenith-trading-bot
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    envVars:
      - key: VITE_APP_API_URL
        value: "https://zenith-bot-backend.onrender.com"